package slotmachine;



/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlotMachine.java
 *
 * Created on 24-Oct-2010, 10:42:31 AM
 */
import java.util.*;
import javax.swing.*;
/**
 *
 * @author admin
 */
public class SlotMachine extends javax.swing.JFrame {
public static int credit = 40;
    /** Creates new form SlotMachine */
    public SlotMachine() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        credits = new javax.swing.JLabel();
        credits1 = new javax.swing.JLabel();
        spin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tokenSelector = new javax.swing.JComboBox();
        slot1 = new javax.swing.JLabel();
        slot2 = new javax.swing.JLabel();
        slot3 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        help = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 255));
        setName("slotMachine"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Rajat's Slot Machine");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        credits.setFont(new java.awt.Font("Tahoma", 1, 18));
        credits.setText("Token Left : ");

        credits1.setBackground(new java.awt.Color(255, 255, 255));
        credits1.setFont(new java.awt.Font("Tahoma", 1, 24));
        credits1.setForeground(new java.awt.Color(255, 51, 51));
        credits1.setText("40");

        spin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spin.setForeground(new java.awt.Color(0, 0, 255));
        spin.setText("Click Here To Play ");
        spin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                spinMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Selelct Number of Tokens ");

        tokenSelector.setFont(new java.awt.Font("Tahoma", 1, 14));
        tokenSelector.setForeground(new java.awt.Color(51, 0, 51));
        tokenSelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5" }));

        slot1.setBackground(new java.awt.Color(102, 102, 255));
        slot1.setFont(new java.awt.Font("Woodcut", 1, 48)); // NOI18N
        slot1.setForeground(new java.awt.Color(0, 0, 255));
        slot1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot1.setText("-");
        slot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));

        slot2.setBackground(new java.awt.Color(255, 255, 0));
        slot2.setFont(new java.awt.Font("Woodcut", 1, 48)); // NOI18N
        slot2.setForeground(new java.awt.Color(0, 0, 255));
        slot2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot2.setText("-");
        slot2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));

        slot3.setBackground(new java.awt.Color(0, 204, 51));
        slot3.setFont(new java.awt.Font("Woodcut", 1, 48)); // NOI18N
        slot3.setForeground(new java.awt.Color(0, 0, 255));
        slot3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slot3.setText("-");
        slot3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 5));
        slot3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(204, 51, 0));
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        help.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        help.setForeground(new java.awt.Color(0, 204, 0));
        help.setText("Help");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tokenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(credits1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(spin)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(exit)
                        .addGap(45, 45, 45)
                        .addComponent(help))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slot3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {slot1, slot2, slot3});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {exit, help});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slot3)
                            .addComponent(slot2)
                            .addComponent(slot1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(credits, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(credits1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(help)
                            .addComponent(exit))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tokenSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                        .addComponent(spin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {slot1, slot2, slot3});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {exit, help});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spinMousePressed
         int numberOfTokenSelected =  tokenSelector.getSelectedIndex()+1;
        System.out.println("number of tokens selected)" + numberOfTokenSelected);
        if (credit < tokenSelector.getSelectedIndex() ){
          JOptionPane.showMessageDialog(null, "Please Change amount of Number of Tokens used.");
      }
 else
     {
        Random rand = new Random();

        int randNum1=rand.nextInt(9);
        int randNum2=rand.nextInt(9);
        int randNum3=rand.nextInt(9);
        slot1.setText(Integer.toString(randNum1));
        slot2.setText(Integer.toString(randNum2));
        slot3.setText(Integer.toString(randNum3));
        credit = credit - numberOfTokenSelected;
        //credit --;
        credits1.setText(Integer.toString(credit));
        if ((randNum1 == randNum2) && (randNum2 == randNum3)) {
            JOptionPane.showMessageDialog(null, "You are a Winner");
         }

        if (credit <= 0) {
           JOptionPane.showMessageDialog(null, "Too many credits used now exiting program.");
           System.exit(1);
         }
    }


    }//GEN-LAST:event_spinMousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpActionPerformed

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(1);
    }//GEN-LAST:event_exitMousePressed

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        JOptionPane.showMessageDialog(null, "First select the 'Number Of Tokens' that you would \nlike to "
                + "play with. The defalt number of tokens is 1. \n Then press 'Click Here To Play' to play."
                + "\n If you wish to exit click the 'Exit' button"
                + "\n Good luck! ");
    }//GEN-LAST:event_helpMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlotMachine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel credits;
    private javax.swing.JLabel credits1;
    private javax.swing.JButton exit;
    private javax.swing.JButton help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel slot1;
    private javax.swing.JLabel slot2;
    private javax.swing.JLabel slot3;
    private javax.swing.JButton spin;
    private javax.swing.JComboBox tokenSelector;
    // End of variables declaration//GEN-END:variables

}
